INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Guépard');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Lion');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Tigre');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Léopard');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Serval');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'Caracal');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Félin', 'chat dore');     
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Bovidés', 'Gazelle');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Bovidés', 'Cob'); 
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Bovidés', 'Yak');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values ('Mammifère', 'Bovidés', 'Gnou');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Orynx');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Zebu');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Koudou');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Antilope');     
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Buffle');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Gayal');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'springbok');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Giraffidés', 'Girafe');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Bovidés', 'Impala');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Éléphantidés', 'Elephant');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Éléphantidés', 'Zèbre des plaines');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Éléphantidés', 'Zèbre des montagnes');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Éléphantidés', 'Zèbre de grévy');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Hippopotamoïdes', 'Hippopotame');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Hyénidés', ' Hyène');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Canidés', 'Chacal à chabraque');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Canidés', 'Lycaon');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Canidés', 'Otocyon');      
   
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Babouin');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Magot');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Cercocèbe');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Drill');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Kipunjii');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Gelada');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Colobe noir');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Colobe blanc');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Colobe olive');


INSERT INTO "associationA"("classeA", "familleA","especeA") values(  'Mammifère', 'Primate', 'Colobes bais'); 
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Microcèbe');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Microcèbre géant');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Allocèbe'); 
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Cheirogale');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Phaner');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Mammifère', 'Primate', 'Lépilémur');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Reptile', 'Crocodilidés', 'Crocodile');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Reptile', 'Carettochelyidae', 'Tortue sillonnée');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Autruche');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Aigle de Cassin');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Akalat brun');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Akalat à tête noire');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Amarante de Reichenow');
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Apalis à calotte noire');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Astrild de Kandt');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Astrild nonnette');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Astrild à tête noire');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Autour à flancs roux'); 
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Autour à longue queue');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Autour de Toussenel');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican bidenté');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican chauve');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican à face rouge');    
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican à gorge grise');   
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican hérissé');  
INSERT INTO "associationA"("classeA", "familleA","especeA") values('Ovipare', 'Oiseaux', 'Barbican à narines emplumées');    

